name: Fullstack Tests (Django + React)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fullstack-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ------------------ BACKEND ------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Django migrations
      working-directory: ./backend
      run: python manage.py migrate

    - name: Start Django backend
      working-directory: ./backend
      run: nohup python manage.py runserver localhost:8000 &

    - name: Wait for backend to be ready
      run: |
        echo "Waiting for Django to start on port 8000..."
        for i in {1..20}; do
          echo "Still waiting..."
          sleep 20
        done

    # ------------------ FRONTEND ------------------
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run Vitest tests
      working-directory: ./frontend
      run: npx vitest run tests
