name: React Dev + Vitest

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run Vitest tests
      working-directory: ./frontend
      run: npx vitest run tests
